### ISSUE TITLE
Testing Problem 1

### ISSUE THREAD

**Issue by Vulcran** [1213-Throwback/Project_5#13]
As a user of this Photo Sharing app I want to see a profiles pictures. However when I try to open that page it stays blank and there is no information provided.

**Comment by DiegoLopezInc** [comment]
As a Scrum Master and QA role I wanted to make sure the pictures are working: 

https://github.com/1213-Throwback/Project_5/assets/123400127/356dd1ef-e46a-40c7-8405-3f2f7e92242f

LGTM! Approved to push to production!

**Comment by Vulcran** [comment]
It looks like the pictures page is loading correctly (aside from pictures overflowing the page). This issue will be resolved as finished

**Comment by ZadokA** [comment]
Problem 1 looks good and satisfies all the requirements listed for problem 1 in project 5.
