### ISSUE TITLE
Testing Problem 2

### ISSUE THREAD

**Issue by Vulcran** [1213-Throwback/Project_5#14]
As a user of the photo sharing platform I want to be able to see different profiles without the page refreshing, but the page reloads when I click a new link

**Comment by DiegoLopezInc** [comment]
As a Scrum Master and QA role I wanted to make sure the pictures are working: 

https://github.com/1213-Throwback/Project_5/assets/123400127/356dd1ef-e46a-40c7-8405-3f2f7e92242f

LGTM! Approved to push to production!

**Comment by Vulcran** [comment]
There is an issue with the pictures going outside of the page border. Fixing the issue now

**Comment by ZadokA** [comment]
As a team member, after reviewing problem 2, it seems to satisfy all the requirements listed in the instructions for project 5.

**Comment by Vulcran** [comment]
As the Developer I have resolved the picture sizing issue and will mark the issue as completed
